### ISSUE TITLE
其他 API 翻译

### ISSUE THREAD

**Issue by SangKa** [RxJS-CN/RxJS-Docs-CN#15]
除 Observable 外的其他所有 API

**Comment by moreJs** [comment]
#16  scheduler 页面完成。

**Comment by moreJs** [comment]
@SangKa 
http://cn.rx.js.org/class/es6/MiscJSDoc.js~SubscribableOrPromiseDoc.html  和 http://cn.rx.js.org/class/es6/MiscJSDoc.js~ObservableInputDoc.html 这个两个页面你翻译了吗？没有的话，我来搞下。

**Comment by SangKa** [comment]
@moreJs 没有，这两个页面的内容都在你之前翻译过的 `MiscJSDoc.ts` 中，都算其他 API 范围了，那就拜托你了

**Comment by moreJs** [comment]
@SangKa  行，那我就搞下 MiscJSDoc.ts。

**Comment by moreJs** [comment]
@SangKa #23 完成，请 review.
