### ISSUE TITLE
翻译高级篇的两节

### ISSUE THREAD

**Issue by SangKa** [RxJS-CN/RxJS-Docs-CN#18]
目标路径：
`doc/writing-marble-tests.md`
`doc/operator-creation.md`

这两节算是高级篇了，内容非常有用，但目前官方没有展示入口，
所以先翻译，至于如果展示还在和官方团队讨论，参见此 [PR](https://github.com/ReactiveX/rxjs/pull/2630)

**Comment by moreJs** [comment]
或者，我们可以先在中文站点展示，
