### ISSUE TITLE
页面内hash跳转链接失效

### ISSUE THREAD

**Issue by ik0r** [RxJS-CN/RxJS-Docs-CN#24]
markdown 生成 html 的时候, 如果标题中没有英文单词, 生成的 id 为 `-`, 导致在页面中跳转时, 无法跳转到页面中的正确位置

**Comment by SangKa** [comment]
确实，hash 是根据 markdown  的 title 生成的，所以翻译完的肯定是有问题的，有英文单词的也一样有问题
