### ISSUE TITLE
生成文档时优化html页面title

### ISSUE THREAD

**Issue by SangKa** [RxJS-CN/RxJS-Docs-CN#27]
目前 ESDoc 生成的中文均是 `RxJS &#x4E2D;&#x6587;&#x6587;&#x6863;` 这样的 html 实体，
会导致 title 中的中文无法很好的被搜索引擎蜘蛛识别，所以需要优化下，在生成 html 文档后用 node 优化 title 。

**Comment by moreJs** [comment]
没找到现成的 plugin, 看样子，要自己写一个了。

**Comment by SangKa** [comment]
是需要自己写个 node 文件，然后成为生成文档的最后一步
