### ISSUE TITLE
提议：中文仓库更新上游仓库的改进方案

### ISSUE THREAD

**Issue by hello-lizhihua** [RxJS-CN/RxJS-Docs-CN#73]
@SangKa 
看到这里的[贡献指南](https://github.com/RxJS-CN/RxJS-Docs-CN/wiki/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97)说是同步更新到 tracking-source 分支。
我有个设想，如果从 tracking-source 分支拉出一个 cn 分支出来，然后在 cn 分支上面翻译。等 tracking-source 有上游更新，再次合并到 cn 分支时，就会提示冲突，然后解决冲突，就可以很方便的感知上游的更新。
可以参考 [webpack-china](https://github.com/webpack-china/webpack.js.org) 的做法（英文 master、中文 master、中文 cn，分别对应我上面说的 master、tracking-source、cn 三个分支）。

**Comment by SangKa** [comment]
@dear-lizhihua 感谢提议！
其实现在的 master 就充当你说的 cn 角色，只是没用 merge， 用的 rebase 。
tracking-source 对应英文 master 。
