### ISSUE TITLE
我们正在组织翻译 rxjs in action，请问 rxjs-cn 是否有人愿意参与进来？

### ISSUE THREAD

**Issue by hello-lizhihua** [RxJS-CN/RxJS-Docs-CN#75]
https://github.com/docschina/rxjs-in-action
我们建立了印记中文QQ群，如果有人愿意参与的话，请加QQ群 492361223。
可以的话，麻烦 @SangKa 帮忙宣传一下，让更多的人参与进来。

**Comment by SangKa** [comment]
@dear-lizhihua 赞，这种好事一定会大力帮推广的，关于这本书我之前和出版社的编辑聊过，国内应该不会引进此书，另外提一个建议和一个问题。
建议是组织翻译前最好制定一个翻译规范，这样后期统一风格上面花的时间会少很多，因为manning的书本身是有内部标准的。
问题是这样直接开源翻译书是否会涉及到版权相关问题？

**Comment by hello-lizhihua** [comment]
翻译流程一直都有，和 [webpack.js.org](https://github.com/webpack-china/webpack.js.org) 的翻译一样，因为是新建的仓库，所以还没有补齐。
版权的事，只能是我们作为私下学习而去翻译，如有侵权，收到通知后立即删除。

**Comment by SangKa** [comment]
@dear-lizhihua  应该是我表述的有问题，不是指翻译配合的流程，是指为manning的书专门准备一套规范 (manning出的书都有固定的格式，代码叫 Listing，代码中都有 ❶ 这样的注解， )，这样大家遵照规范进行翻译，后期可以少返工。
版权的话我感觉其实是有侵权，但个人而言我是大力支持的。
这本书内容不少，最后祝你们翻译顺利，时间允许的话我也会参与其中。

**Comment by hello-lizhihua** [comment]
好的，感谢！

**Comment by dear-lizhihua** [comment]
可以加我，我们建了一个微信群，里面有100多人，也可以看有没有对 rxjs-cn 的文档翻译感兴趣的。
