### ISSUE TITLE
邀请您加入docschina共同维护rxjs和mobx中文文档

### ISSUE THREAD

**Issue by lcxfs1991** [RxJS-CN/RxJS-Docs-CN#85]
你好，我是来自印记中文 docschina 的 heyli，目前就职于腾讯 AlloyTeam。感谢您为 rxjs 与 mobx中文文档做的贡献，希望邀请你一起共同维护 rxjs 与 mobx 文档，一起整合社区翻译资源及人才，打造更好的技术文档翻译社区。如有兴趣，可添加QQ: 249806703 或 微信：lcxfs1991。

**Comment by lcxfs1991** [comment]
: )  问了下核心成员，好像已经把你加群里了。我加你一下微信哈。

**Comment by SangKa** [comment]
@lcxfs1991 已加 微信聊吧
